remote: true

experienceLevel:
 internship: false
 entry: true
 associate: true
 mid-senior level: false
 director: false
 executive: false

jobTypes:
 full-time: true
 contract: false
 part-time: false
 temporary: false
 internship: false
 other: true
 volunteer: false

date:
 all time: true
 month: true
 week: true
 24 hours: true

positions:
  - Data Scientist
  - AI Engineer

locations:
  - India

distance: 100

companyBlacklist:


titleBlacklist:
